# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ai_companion_uikit' do
  project 'ai_companion_uikit.xcodeproj'
  workspace 'ai_companion_oc.xcworkspace'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ai_companion_oc
  pod 'ZIMKit',:path => './Libs/zego_uikit_ios/zego_zimkit'
  pod 'Masonry', '1.1.0'
  pod 'YYKit', '1.0.9'
  pod 'SSZipArchive'
end

target 'ai_companion_express' do
  project 'ai_companion_express.xcodeproj'
  workspace 'ai_companion_oc.xcworkspace'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ai_companion_oc
  pod 'Masonry', '1.1.0'
  pod 'YYKit', '1.0.9'
  pod 'SSZipArchive'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
    end
  end
end
